id: IBE1B1BE1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T13:46:57+00:00'
last_modified: '2022-06-07T10:38:25.347106+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23450
  title: དཔལ་ཡུལ་ཆོས་སྤྱོད་༔་ཅོལླེཅཏེད་ལིཏུརྒིཅལ་ཏེ྾ཙ་རེཅིཏེད་ཨཏ་ཐེ་མོནསྟེརཡ་དཔལ་ཡུལ་ཨིན་ཁམས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    192A:
      image_group_id: I1KG1377
      title: 'Volume 1 of dpal yul chos spyod : collected liturgical texts receited
        at the monastery dpal yul in khams'
      total_pages: 880
      order: 1
      base_file: 192A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
